[[product]]
identifier = "budget"
name = "M-Budget Energy Drink"
price = 50

[[product]]
identifier = "kong"
name = "Kong Strong Energy Drink"
price = 50

[[product]]
identifier = "cola"
name = "Cola Zero"
price = 70

[[product]]
identifier = "caprisun"
name = "Capri Sonne"
price = 50

[[product]]
identifier = "noir"
name = "Noir Special Riegel"
price = 80

[[product]]
identifier = "gipfel"
name = "Nuss-Nougat Croissant"
price = 30

[[product]]
identifier = "snickers"
name = "Snickers"
price = 50

[[product]]
identifier = "mars"
name = "Mars"
price = 50

[[product]]
identifier = "twix"
name = "Twix"
price = 50

[[product]]
identifier = "hanuta"
name = "Hanuta"
price = 30

[[product]]
identifier = "farmer"
name = "Farmer Soft"
price = 50

[[product]]
identifier = "schoggi"
name = "Choco Drink"
price = 50
